apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: node-express
  namespace: dev
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/my-sp: "true"
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    app.kubernetes.io/part-of: node-express
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  - name: testing_pipeline_matching_labels
    value:
      # apps.tanzu.vmware.com/pipeline: test
      apps.tanzu.vmware.com/language: node
  source:
    git:
      url: https://github.com/SergeyMuha/node.git
      ref:
        branch: master
